/**
 * Suricat icons — react-icons (Font Awesome 6 style).
 * Prefer importing named icons; use resolveFaIcon() for Designs string keys.
 */
export {
  FaAnglesRight,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaArrowUpRightFromSquare,
  FaAward,
  FaBars,
  FaBellConcierge,
  FaBellSlash,
  FaBolt,
  FaBrain,
  FaBuilding,
  FaBullseye,
  FaCalendarCheck,
  FaCalendarDays,
  FaCalendarXmark,
  FaCertificate,
  FaChartColumn,
  FaChartLine,
  FaCheck,
  FaCheckDouble,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaCircleCheck,
  FaCircleExclamation,
  FaCircleInfo,
  FaCircleUser,
  FaClipboardCheck,
  FaClipboardList,
  FaClock,
  FaClockRotateLeft,
  FaCodeBranch,
  FaCommentDots,
  FaComments,
  FaCompassDrafting,
  FaCrosshairs,
  FaDatabase,
  FaDiagramProject,
  FaDna,
  FaEarthAmericas,
  FaEnvelope,
  FaEye,
  FaEyeSlash,
  FaFileCircleCheck,
  FaFileCircleExclamation,
  FaFileImport,
  FaFileLines,
  FaFileMedical,
  FaFileShield,
  FaFlask,
  FaFolderOpen,
  FaGaugeHigh,
  FaGear,
  FaGlobe,
  FaHandshake,
  FaHeadset,
  FaHeartPulse,
  FaHourglassEnd,
  FaHourglassHalf,
  FaIndustry,
  FaLayerGroup,
  FaLink,
  FaLinkSlash,
  FaLocationDot,
  FaLock,
  FaMagnifyingGlass,
  FaMagnifyingGlassChart,
  FaMagnifyingGlassMinus,
  FaMicroscope,
  FaNetworkWired,
  FaPaperPlane,
  FaPersonDigging,
  FaPills,
  FaPlane,
  FaPuzzlePiece,
  FaRotate,
  FaRoute,
  FaShareNodes,
  FaShieldHalved,
  FaSitemap,
  FaStar,
  FaTimeline,
  FaTriangleExclamation,
  FaUser,
  FaUserCheck,
  FaUserDoctor,
  FaUserGraduate,
  FaUserTie,
  FaUsers,
  FaWaveSquare,
  FaXmark,
  FaUpRightFromSquare,
  FaBuildingColumns,
} from "react-icons/fa6";

/** Lifecycle timeline (Designs medical-devices) */
export { FaScrewdriverWrench } from "react-icons/fa6";

/** Alias for Designs fa-angle-double-right */
export { FaAnglesRight as FaAngleDoubleRight } from "react-icons/fa6";

/** Designs class-name aliases */
export { FaGear as FaCog } from "react-icons/fa6";
export { FaShieldHalved as FaShieldAlt } from "react-icons/fa6";
export { FaFileLines as FaFileAlt } from "react-icons/fa6";
export { FaCircleCheck as FaCheckCircle } from "react-icons/fa6";
export { FaUpRightFromSquare as FaExternalLinkAlt } from "react-icons/fa6";
export { FaCircleInfo as FaInfoCircle } from "react-icons/fa6";
/** Free FA6 stand-ins for Pro-only Designs glyphs */
export { FaChartColumn as FaChartMixed } from "react-icons/fa6";
export { FaMagnifyingGlassChart as FaMagnifyingGlassClock } from "react-icons/fa6";

export {
  FaFacebookF,
  FaLinkedinIn,
  FaTimes,
  FaTwitter,
  FaYoutube,
} from "react-icons/fa";

/** Solid FA6 glyph for Designs fa-code-fork */
export { FaCodeFork } from "react-icons/fa6";

/** Regular (outline) FA6 icons — Designs use far / fa-regular for these */
export {
  FaRegCalendar,
  FaRegCalendarCheck,
  FaRegCircleCheck,
  FaRegCircleUser,
  FaRegClock,
  FaRegEnvelope,
  FaRegEye,
  FaRegEyeSlash,
  FaRegFileLines,
  FaRegUser,
} from "react-icons/fa6";

/** Material Design outline icons (Designs contact / mission-vision / industries via iconify mdi) */
export {
  MdOutlineAccountBalance,
  MdOutlineBolt,
  MdOutlineDescription,
  MdOutlineEmail,
  MdOutlineGroups,
  MdOutlineInfo,
  MdOutlineLocationOn,
  MdOutlineStorage,
  MdOutlineLanguage,
} from "react-icons/md";

import type { IconType } from "react-icons";
import {
  FaAward,
  FaBellConcierge,
  FaBellSlash,
  FaBolt,
  FaBrain,
  FaBuilding,
  FaBullseye,
  FaCalendarCheck,
  FaCalendarXmark,
  FaCertificate,
  FaChartColumn,
  FaChartLine,
  FaCheck,
  FaCheckDouble,
  FaCircleCheck,
  FaCircleExclamation,
  FaCircleInfo,
  FaCircleUser,
  FaClipboardCheck,
  FaClipboardList,
  FaClock,
  FaClockRotateLeft,
  FaCodeBranch,
  FaCommentDots,
  FaComments,
  FaCompassDrafting,
  FaDiagramProject,
  FaEnvelope,
  FaEye,
  FaEyeSlash,
  FaFileCircleCheck,
  FaFileLines,
  FaFileMedical,
  FaFileShield,
  FaFlask,
  FaGaugeHigh,
  FaGear,
  FaHeadset,
  FaHourglassEnd,
  FaHourglassHalf,
  FaIndustry,
  FaLayerGroup,
  FaLink,
  FaLinkSlash,
  FaLock,
  FaMagnifyingGlass,
  FaMagnifyingGlassChart,
  FaMagnifyingGlassMinus,
  FaNetworkWired,
  FaPaperPlane,
  FaPersonDigging,
  FaPuzzlePiece,
  FaRotate,
  FaRoute,
  FaScrewdriverWrench,
  FaShareNodes,
  FaShieldHalved,
  FaSitemap,
  FaStar,
  FaTimeline,
  FaTriangleExclamation,
  FaUserCheck,
  FaUserGraduate,
  FaUserTie,
  FaUsers,
  FaWaveSquare,
} from "react-icons/fa6";

const dynamicMap: Record<string, IconType> = {
  "fa-award": FaAward,
  award: FaAward,
  "fa-bell-concierge": FaBellConcierge,
  "fa-bell-slash": FaBellSlash,
  "fa-bolt": FaBolt,
  bolt: FaBolt,
  "fa-brain": FaBrain,
  "fa-building": FaBuilding,
  "fa-bullseye": FaBullseye,
  bullseye: FaBullseye,
  "fa-calendar-check": FaCalendarCheck,
  "fa-calendar-xmark": FaCalendarXmark,
  "fa-certificate": FaCertificate,
  "fa-chart-column": FaChartColumn,
  "fa-chart-line": FaChartLine,
  "fa-chart-mixed": FaChartColumn,
  "fa-check": FaCheck,
  check: FaCheck,
  "fa-check-circle": FaCircleCheck,
  "fa-check-double": FaCheckDouble,
  "fa-circle-check": FaCircleCheck,
  "fa-circle-exclamation": FaCircleExclamation,
  "fa-circle-info": FaCircleInfo,
  "fa-circle-user": FaCircleUser,
  "fa-clipboard-check": FaClipboardCheck,
  "fa-clipboard-list": FaClipboardList,
  "fa-clock": FaClock,
  "fa-clock-rotate-left": FaClockRotateLeft,
  "fa-code-branch": FaCodeBranch,
  "fa-cog": FaGear,
  "fa-comment-dots": FaCommentDots,
  "fa-comments": FaComments,
  "fa-compass-drafting": FaCompassDrafting,
  "fa-diagram-project": FaDiagramProject,
  "fa-envelope": FaEnvelope,
  "fa-eye": FaEye,
  eye: FaEye,
  "fa-eye-slash": FaEyeSlash,
  "fa-file-alt": FaFileLines,
  "fa-file-circle-check": FaFileCircleCheck,
  "fa-file-lines": FaFileLines,
  "fa-file-medical": FaFileMedical,
  "fa-file-shield": FaFileShield,
  "fa-flask": FaFlask,
  "fa-gauge-high": FaGaugeHigh,
  "fa-gear": FaGear,
  "fa-headset": FaHeadset,
  "fa-hourglass-end": FaHourglassEnd,
  "fa-hourglass-half": FaHourglassHalf,
  "fa-industry": FaIndustry,
  "fa-info-circle": FaCircleInfo,
  "fa-layer-group": FaLayerGroup,
  "fa-link": FaLink,
  "fa-link-slash": FaLinkSlash,
  "fa-lock": FaLock,
  "fa-magnifying-glass": FaMagnifyingGlass,
  "fa-magnifying-glass-chart": FaMagnifyingGlassChart,
  "fa-magnifying-glass-clock": FaMagnifyingGlassChart,
  "fa-magnifying-glass-minus": FaMagnifyingGlassMinus,
  "fa-network-wired": FaNetworkWired,
  "fa-paper-plane": FaPaperPlane,
  "fa-person-digging": FaPersonDigging,
  "fa-puzzle-piece": FaPuzzlePiece,
  "fa-rotate": FaRotate,
  "fa-route": FaRoute,
  "fa-screwdriver-wrench": FaScrewdriverWrench,
  "fa-share-nodes": FaShareNodes,
  "fa-shield-alt": FaShieldHalved,
  "fa-shield-halved": FaShieldHalved,
  "fa-sitemap": FaSitemap,
  "fa-star": FaStar,
  "fa-timeline": FaTimeline,
  "fa-triangle-exclamation": FaTriangleExclamation,
  "fa-user-check": FaUserCheck,
  "fa-user-graduate": FaUserGraduate,
  "fa-user-tie": FaUserTie,
  "fa-users": FaUsers,
  "fa-wave-square": FaWaveSquare,
};

export function resolveFaIcon(name: string): IconType {
  const key = name
    .replace(/^(fas|far|fab|fa-solid|fa-regular)\s+/, "")
    .trim();
  return dynamicMap[key] ?? dynamicMap[key.replace(/^fa-/, "")] ?? FaCheck;
}
